version: '3.7'
services:
    app:
        build: ./app
        ports:
          - "5001:5000"
    app2:
       build: ./app2
       ports:
         - "5002:5000"
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - 80:80
        depends_on:
           - app
           - app2
